os:
  - linux
  - osx
sudo: false
dist: trusty
language:
  - java
jdk:
  - oraclejdk8  # Building Bazel requires JDK8.
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8'
        key_url: 'https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg'
    packages:
      - bazel
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bazel; fi
script:
  - bazel build //...
  - bazel test --test_output=errors //...
